- name: Swap Off
  ansible.builtin.shell: swapoff -a

- name: Update repositories
  ansible.builtin.apt:
    update_cache: yes

- name: Install Requirements for kubeadm
  ansible.builtin.apt:
    pkg:
    - apt-transport-https
    - ca-certificates
    - curl

- name: Create directory for apt
  file:
    path: /etc/apt/keyrings
    state: directory

- name: Download the Google Cloud public signing key
  ansible.builtin.shell: "curl -fsSLo /etc/apt/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg"

- name: Add the Kubernetes apt repository
  ansible.builtin.shell: echo "deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list

- name: Update repositories
  ansible.builtin.apt:
    update_cache: yes

- name: Install Requirements for kubeadm
  ansible.builtin.apt:
    pkg:
    - kubeadm=1.26.0-00
    - kubelet=1.26.0-00
    - kubectl=1.26.0-00